# Generated by Django 4.0.8 on 2025-11-19 13:09

from django.db import migrations, connection

def drop_payments_invoice(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS payments_invoice;")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsandevents_summary_es_newsandevents_summary_fr_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_payments_invoice),
    ]
