# Generated by Django 5.1.2 on 2025-11-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_drop_payments_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre visible del piso. Ej: Planta baja, Primer piso.",
                        max_length=120,
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        help_text="Número de piso dentro del edificio (0 = PB, 1 = primer piso, etc.)."
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("number",),
                "verbose_name": "Piso",
                "verbose_name_plural": "Pisos",
                "unique_together": {("name", "number")},
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador único del aula/laboratorio.",
                        max_length=50,
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[("CLASSROOM", "Aula"), ("LAB", "Laboratorio")],
                        default="CLASSROOM",
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Capacidad máxima de personas."
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el espacio está habilitado para uso.",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="core.buildingfloor",
                        verbose_name="Piso",
                    ),
                ),
            ],
            options={
                "ordering": ("floor__number", "code"),
                "verbose_name": "Aula / Laboratorio",
                "verbose_name_plural": "Aulas y Laboratorios",
                "unique_together": {("floor", "code")},
            },
        ),
    ]
