# Generated by Django 4.0.8 on 2025-11-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_building_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_ru',
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('First', '1º Cuatrimestre'), ('Second', '2º Cuatrimestre'), ('Third', '3º Cuatrimestre')], max_length=10),
        ),
    ]
