# Generated by Django 4.0.8 on 2025-11-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_newsandevents_summary_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('FIRST', '1° Cuatrimestre'), ('SECOND', '2° Cuatrimestre'), ('SUMMER', 'Materias de Verano')], max_length=10),
        ),
    ]
