# Generated by Django 4.0.8 on 2025-11-19 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_alter_course_semester'),
        ('core', '0007_alter_semester_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsandevents',
            options={'ordering': ('-updated_date',)},
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='audience_roles',
            field=models.JSONField(blank=True, default=list, help_text='Roles destinatarios (coordinadores, docentes, alumnos, etc.). Si queda vacío se usarán los filtros de carrera o materia.'),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Permite que la publicación sea visible para toda la comunidad.'),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='target_courses',
            field=models.ManyToManyField(blank=True, help_text='Filtra la publicación para materias/comisiones específicas.', related_name='news_items', to='course.course'),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='target_programs',
            field=models.ManyToManyField(blank=True, help_text='Filtra la publicación para una o varias carreras.', related_name='news_items', to='course.program'),
        ),
    ]
