# Generated by Django 4.0.8 on 2025-11-19 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_programs_as_coordinator'),
        ('course', '0010_course_evaluation_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_newsandevents_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.coursesection')),
            ],
            options={
                'verbose_name': 'Clase programada',
                'verbose_name_plural': 'Clases programadas',
                'ordering': ('-date', '-start_time'),
                'unique_together': {('section', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BulkUploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ATTENDANCE', 'Asistencia'), ('GRADES', 'Notas de exámenes'), ('ENROLLMENT', 'Asignación de alumnos')], max_length=20)),
                ('file', models.FileField(upload_to='ai_uploads/%Y/%m/')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('PROCESSING', 'En procesamiento IA'), ('COMPLETED', 'Procesado')], default='RECEIVED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='course.coursesection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga asistida por IA',
                'verbose_name_plural': 'Cargas asistidas por IA',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('JUSTIFIED', 'Justificado')], default='PRESENT', max_length=15)),
                ('comment', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.sectionsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ('-recorded_at',),
                'unique_together': {('session', 'student')},
            },
        ),
    ]
