# Generated by Django 4.0.8 on 2025-11-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_evaluation_mode_and_more'),
        ('accounts', '0007_remove_user_programs_as_coordinator'),
        ('core', '0009_sectionsession_bulkuploadrequest_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='target_sections',
            field=models.ManyToManyField(blank=True, help_text='Filtra la publicación para comisiones específicas.', related_name='news_items', to='course.coursesection'),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='target_courses',
            field=models.ManyToManyField(blank=True, help_text='Filtra la publicación para materias específicas.', related_name='news_items', to='course.course'),
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Confirmado'), ('DECLINED', 'No asistirá')], default='PENDING', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invitations', to='core.newsandevents')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invitations', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Invitación a evento',
                'verbose_name_plural': 'Invitaciones a eventos',
                'unique_together': {('event', 'student')},
            },
        ),
    ]
