# Generated by Django 4.0.8 on 2025-11-20 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_newsandevents_target_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='justification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='sectionsession',
            name='attendance_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AttendanceJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_comment', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='justificaciones/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='core.attendancerecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Justificación de asistencia',
                'verbose_name_plural': 'Justificaciones de asistencia',
            },
        ),
        migrations.CreateModel(
            name='AttendanceReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='core.sectionsession')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recordatorio de asistencia',
                'verbose_name_plural': 'Recordatorios de asistencia',
                'unique_together': {('teacher', 'session')},
            },
        ),
    ]
