# Generated by Django 4.0.8 on 2025-11-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attendancerecord_justification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='next_semester_begins',
        ),
        migrations.RemoveField(
            model_name='session',
            name='next_session_begins',
        ),
    ]
