# Generated by Django 4.0.8 on 2025-11-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_prerequisites_course_programs_and_more'),
        ('core', '0013_add_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancejustification',
            options={'verbose_name': 'Justificación de asistencia', 'verbose_name_plural': 'Justificaciones de asistencia'},
        ),
        migrations.AlterModelOptions(
            name='eventinvitation',
            options={'verbose_name': 'Invitación a evento', 'verbose_name_plural': 'Invitaciones a eventos'},
        ),
        migrations.AlterField(
            model_name='buildingfloor',
            name='number',
            field=models.IntegerField(help_text='Número de piso dentro del edificio (0 = PB, 1 = primer piso, etc.).'),
        ),
        migrations.AlterField(
            model_name='bulkuploadrequest',
            name='kind',
            field=models.CharField(choices=[('ATTENDANCE', 'Asistencia'), ('GRADES', 'Notas de exámenes'), ('ENROLLMENT', 'Asignación de alumnos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventinvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Confirmado'), ('DECLINED', 'No asistirá')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='audience_roles',
            field=models.JSONField(blank=True, default=list, help_text='Roles destinatarios (coordinadores, docentes, alumnos, etc.). Si queda vacío se usarán los filtros de carrera o materia.'),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Permite que la publicación sea visible para toda la comunidad.'),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='target_courses',
            field=models.ManyToManyField(blank=True, help_text='Filtra la publicación para materias específicas.', related_name='news_items', to='course.course'),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='target_programs',
            field=models.ManyToManyField(blank=True, help_text='Filtra la publicación para una o varias carreras.', related_name='news_items', to='course.program'),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='target_sections',
            field=models.ManyToManyField(blank=True, help_text='Filtra la publicación para comisiones específicas.', related_name='news_items', to='course.coursesection'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(help_text='Identificador único del espacio.', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Indica si el espacio está habilitado para uso.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('CLASSROOM', 'Aula'), ('LAB', 'Laboratorio'), ('OTHER', 'Otro')], default='CLASSROOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('FIRST', '1° Cuatrimestre'), ('SECOND', '2° Cuatrimestre'), ('SUMMER', 'Materias de Verano')], max_length=10),
        ),
    ]
