# Generated by Django 5.1.2 on 2025-11-21 21:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_student_programs"),
        ("core", "0014_alter_attendancejustification_options_and_more"),
        ("course", "0015_alter_coursesection_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancejustification",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Justificación de inasistencia",
                "verbose_name_plural": "Justificaciones de inasistencia",
            },
        ),
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Registro de asistencia",
                "verbose_name_plural": "Registros de asistencia",
            },
        ),
        migrations.AlterModelOptions(
            name="attendancereminderlog",
            options={
                "ordering": ("-sent_at",),
                "verbose_name": "Recordatorio de asistencia",
                "verbose_name_plural": "Recordatorios de asistencia",
            },
        ),
        migrations.AlterModelOptions(
            name="buildingfloor",
            options={
                "ordering": ("number", "name"),
                "verbose_name": "Piso / Nivel",
                "verbose_name_plural": "Pisos / Niveles",
            },
        ),
        migrations.AlterModelOptions(
            name="bulkuploadrequest",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Carga masiva",
                "verbose_name_plural": "Cargas masivas",
            },
        ),
        migrations.AlterModelOptions(
            name="newsandevents",
            options={},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ("code",),
                "verbose_name": "Espacio",
                "verbose_name_plural": "Espacios",
            },
        ),
        migrations.AlterModelOptions(
            name="sectionsession",
            options={
                "ordering": ("-date", "-start_time"),
                "verbose_name": "Clase de comisión",
                "verbose_name_plural": "Clases de comisión",
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendancereminderlog",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="buildingfloor",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sectionsession",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="attendancejustification",
            name="attendance_record",
        ),
        migrations.RemoveField(
            model_name="attendancejustification",
            name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="attendancejustification",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="justification_token",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="recorded_at",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="recorded_by",
        ),
        migrations.RemoveField(
            model_name="bulkuploadrequest",
            name="processed_at",
        ),
        migrations.RemoveField(
            model_name="bulkuploadrequest",
            name="section",
        ),
        migrations.RemoveField(
            model_name="bulkuploadrequest",
            name="status",
        ),
        migrations.RemoveField(
            model_name="bulkuploadrequest",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="created_by",
        ),
        migrations.AddField(
            model_name="attendancejustification",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="justifications",
                to="core.attendancerecord",
            ),
        ),
        migrations.AddField(
            model_name="attendancejustification",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancejustification",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absence_justifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancejustification",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="course.coursesection",
            ),
        ),
        migrations.AddField(
            model_name="attendancereminderlog",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="attendancereminderlog",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="course.coursesection",
            ),
        ),
        migrations.AddField(
            model_name="bulkuploadrequest",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulk_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="invite_students",
            field=models.ManyToManyField(
                blank=True, related_name="event_invitations_news", to="accounts.student"
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="next_semester_begins",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="next_session_begins",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancejustification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancejustification",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="justifications/"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="core.sectionsession",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Presente"),
                    ("ABSENT", "Ausente"),
                    ("LATE", "Llegó tarde"),
                ],
                default="PRESENT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attendancereminderlog",
            name="sent_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="attendancereminderlog",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="buildingfloor",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="buildingfloor",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="buildingfloor",
            name="number",
            field=models.IntegerField(verbose_name="Piso"),
        ),
        migrations.AlterField(
            model_name="bulkuploadrequest",
            name="file",
            field=models.FileField(upload_to="bulk_uploads/"),
        ),
        migrations.AlterField(
            model_name="bulkuploadrequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ATTENDANCE", "Asistencia"),
                    ("GRADES", "Notas"),
                    ("ENROLLMENT", "Inscripciones"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventinvitation",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="core.newsandevents",
            ),
        ),
        migrations.AlterField(
            model_name="eventinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("ACCEPTED", "Aceptada"),
                    ("DECLINED", "Rechazada"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="eventinvitation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="audience_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="target_courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="news_courses",
                to="course.course",
                verbose_name="Materias",
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="target_programs",
            field=models.ManyToManyField(
                blank=True,
                related_name="news_targets",
                to="course.program",
                verbose_name="Carreras",
            ),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="target_sections",
            field=models.ManyToManyField(
                blank=True,
                related_name="news_sections",
                to="course.coursesection",
                verbose_name="Comisiones",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(max_length=100, unique=True, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="core.buildingfloor",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="sectionsession",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="sectionsession",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="semester",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIRST", "1º Cuatrimestre"),
                    ("SECOND", "2º Cuatrimestre"),
                    ("SUMMER", "Materias de Verano"),
                ],
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="attendancereminderlog",
            name="session",
        ),
        migrations.RemoveField(
            model_name="sectionsession",
            name="attendance_submitted",
        ),
        migrations.RemoveField(
            model_name="sectionsession",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sectionsession",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="sectionsession",
            name="is_cancelled",
        ),
        migrations.RemoveField(
            model_name="sectionsession",
            name="updated_at",
        ),
    ]
