# Generated by Django 5.1.2 on 2025-11-21 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_attendancejustification_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Registro de actividad",
                "verbose_name_plural": "Registros de actividad",
            },
        ),
        migrations.AlterModelOptions(
            name="attendancejustification",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Justificacion de inasistencia",
                "verbose_name_plural": "Justificaciones de inasistencia",
            },
        ),
        migrations.AlterModelOptions(
            name="eventinvitation",
            options={
                "verbose_name": "Invitacion a evento",
                "verbose_name_plural": "Invitaciones a eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="newsandevents",
            options={
                "ordering": ("-upload_time",),
                "verbose_name": "Noticia o evento",
                "verbose_name_plural": "Noticias y eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="sectionsession",
            options={
                "ordering": ("-date", "-start_time"),
                "verbose_name": "Clase de comision",
                "verbose_name_plural": "Clases de comision",
            },
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={
                "ordering": ("-session__session", "semester"),
                "verbose_name": "Cuatrimestre",
                "verbose_name_plural": "Cuatrimestres",
            },
        ),
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ("-session",),
                "verbose_name": "Ciclo lectivo",
                "verbose_name_plural": "Ciclos lectivos",
            },
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Presente"),
                    ("ABSENT", "Ausente"),
                    ("LATE", "Llego tarde"),
                ],
                default="PRESENT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="buildingfloor",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripcion"),
        ),
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(max_length=100, unique=True, verbose_name="Codigo"),
        ),
        migrations.AlterField(
            model_name="semester",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIRST", "1er Cuatrimestre"),
                    ("SECOND", "2do Cuatrimestre"),
                    ("SUMMER", "Materias de Verano"),
                ],
                max_length=10,
            ),
        ),
    ]
