# Generated by Django 5.1.2 on 2025-11-24 23:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_activitylog_options_and_more"),
        ("course", "0015_alter_coursesection_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancejustification",
            name="attendance",
        ),
        migrations.AddField(
            model_name="attendancejustification",
            name="attendance_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="justifications",
                to="core.attendancerecord",
            ),
        ),
        migrations.AddField(
            model_name="attendancejustification",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancejustification",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="justifications_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="justification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bulkuploadrequest",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_uploads",
                to="course.coursesection",
            ),
        ),
        migrations.AddField(
            model_name="bulkuploadrequest",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulk_uploads_uploaded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sectionsession",
            name="attendance_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sectionsession",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Presente"),
                    ("ABSENT", "Ausente"),
                    ("LATE", "Llego tarde"),
                    ("JUSTIFIED", "Justificada"),
                ],
                default="PRESENT",
                max_length=10,
            ),
        ),
    ]
