# Generated by Django 5.1.2 on 2025-11-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_attendancejustification_attendance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkuploadrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Recibido"),
                    ("PROCESSING", "Procesando"),
                    ("COMPLETED", "Completado"),
                    ("FAILED", "Fallido"),
                ],
                default="RECEIVED",
                help_text="Estado de procesamiento de la carga.",
                max_length=20,
            ),
        ),
    ]
