# Generated by Django 5.1.2 on 2025-11-28 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_bulkuploadrequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha desde")),
                ("end_date", models.DateField(verbose_name="Fecha hasta")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Hora inicio"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="Hora fin"),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="Motivo"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_blocks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="core.room",
                        verbose_name="Espacio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloqueo de espacio",
                "verbose_name_plural": "Bloqueos de espacios",
                "ordering": ("-start_date", "-start_time"),
            },
        ),
    ]
