# Generated by Django 5.1.2 on 2025-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_roomblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkuploadrequest",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulkuploadrequest",
            name="result_log",
            field=models.TextField(blank=True),
        ),
    ]
