# Generated by Django 4.0.8 on 2025-11-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_summary_en_remove_course_summary_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'Primer Cuatrimestre'), ('Second', 'Segundo Cuatrimestre'), ('Third', 'Materias de Verano')], max_length=200),
        ),
    ]
