# Generated by Django 4.0.8 on 2025-11-19 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('short_name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='program',
            name='allows_promotion',
            field=models.BooleanField(default=True, help_text='Indica si la carrera permite promocionar materias sin final.'),
        ),
        migrations.AddField(
            model_name='program',
            name='min_passing_attendance',
            field=models.PositiveIntegerField(default=75, help_text='Porcentaje de asistencia requerido para aprobar.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='program',
            name='min_promotion_attendance',
            field=models.PositiveIntegerField(default=80, help_text='Porcentaje de asistencia requerido para promocionar.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='program',
            name='pass_score',
            field=models.DecimalField(decimal_places=1, default=4.0, help_text='Nota mínima para aprobar (0 a 10).', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('TEC', 'Tecnicatura'), ('LIC', 'Licenciatura')], default='TEC', max_length=3),
        ),
        migrations.AddField(
            model_name='program',
            name='promotion_score',
            field=models.DecimalField(decimal_places=1, default=6.0, help_text='Nota mínima para promocionar (0 a 10).', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='course.university'),
        ),
    ]
