# Generated by Django 4.0.8 on 2025-11-19 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_newsandevents_options_and_more'),
        ('course', '0007_university_program_allows_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Carrera para la cual se realiza la asignación.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='course.program'),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text="Lista de días de cursada (ej: ['Lunes','Miércoles']).")),
                ('max_capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.course')),
                ('program', models.ForeignKey(help_text='Carrera responsable de la comisión.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.program')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='core.room')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='core.semester')),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_sections', to=settings.AUTH_USER_MODEL)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='course.turn')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ('-created_at',),
            },
        ),
    ]
