# Generated by Django 4.0.8 on 2025-11-19 19:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_turn_courseallocation_program_coursesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ('-created_at',), 'verbose_name': 'Comisión', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AddField(
            model_name='program',
            name='coordinators',
            field=models.ManyToManyField(blank=True, help_text='Seleccioná uno o más coordinadores responsables de la carrera.', limit_choices_to={'role': 'COORDINATOR'}, related_name='programs_coordinated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Carrera para la cual se realiza la asignación.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='course.program'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text="Lista de días de cursada (ej: ['Lunes','Miércoles'])."),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='program',
            field=models.ForeignKey(help_text='Carrera responsable de la comisión.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='pass_score',
            field=models.DecimalField(decimal_places=1, default=4.0, help_text='Nota mínima para aprobar (0 a 10).', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='program',
            name='promotion_score',
            field=models.DecimalField(decimal_places=1, default=6.0, help_text='Nota mínima para promocionar (0 a 10).', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(help_text='Archivos válidos: pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip', upload_to='course_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])]),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(help_text='Formatos de video válidos: mp4, mkv, wmv, 3gp, f4v, avi, mp3', upload_to='course_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])]),
        ),
    ]
