# Generated by Django 4.0.8 on 2025-11-20 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_evaluation_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallocation',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Carrera para la cual se realiza la asignación.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='course.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='pass_score',
            field=models.DecimalField(decimal_places=1, default=4.0, help_text='Nota mí\xadnima para aprobar (0 a 10).', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('TEC', 'Tecnicatura'), ('LIC', 'Licenciatura'), ('DIP', 'Diplomatura'), ('ING', 'Curso de ingreso')], default='TEC', max_length=3),
        ),
    ]
