# Generated by Django 4.0.8 on 2025-11-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_courseallocation_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Seleccione correlativas si las hubiera.', related_name='dependent_courses', to='course.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Seleccione una o varias carreras a las que pertenece la materia.', related_name='courses', to='course.program'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='Marca si la materia es electiva dentro de la carrera.', verbose_name='Materia electiva'),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Carrera principal (opcional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_courses', to='course.program'),
        ),
    ]
