# Generated by Django 4.0.8 on 2025-11-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_coursesection_code_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='code',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='students',
        ),
    ]
