# Generated by Django 5.1.2 on 2025-11-21 20:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0014_remove_coursesection_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursesection",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "ComisiÃ³n",
                "verbose_name_plural": "Comisiones",
            },
        ),
        migrations.AlterModelOptions(
            name="examschedule",
            options={
                "ordering": ("-date", "-start_time"),
                "verbose_name": "Examen",
                "verbose_name_plural": "ExÃ¡menes",
            },
        ),
        migrations.AddField(
            model_name="coursesection",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="CÃ³digo identificador de la comisiÃ³n.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seleccione los alumnos inscriptos en esta comisiÃ³n.",
                limit_choices_to={"role": "STUDENT"},
                related_name="sections_enrolled",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Alumnos",
            ),
        ),
        migrations.AlterField(
            model_name="courseallocation",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="Carrera para la cual se realiza la asignaciÃ³n.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="course.program",
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="attendance_required",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Porcentaje mÃ\xadnimo de asistencia para aprobar la comisiÃ³n.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de dÃ\xadas de cursada (ej: ['Lunes','MiÃ©rcoles']).",
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="program",
            field=models.ForeignKey(
                help_text="Carrera responsable de la comisiÃ³n.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="course.program",
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="promotion_attendance_required",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Porcentaje mÃ\xadnimo de asistencia para promocionar la comisiÃ³n.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="coordinators",
            field=models.ManyToManyField(
                blank=True,
                help_text="SeleccionÃ¡ uno o mÃ¡s coordinadores responsables de la carrera.",
                limit_choices_to={"role": "COORDINATOR"},
                related_name="programs_coordinated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="pass_score",
            field=models.DecimalField(
                decimal_places=1,
                default=4.0,
                help_text="Nota mÃ\xadÂ\xadnima para aprobar (0 a 10).",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="promotion_score",
            field=models.DecimalField(
                decimal_places=1,
                default=6.0,
                help_text="Nota mÃ\xadnima para promocionar (0 a 10).",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(
                help_text="Archivos vÃ¡lidos: pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip",
                upload_to="course_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "docx",
                            "doc",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "zip",
                            "rar",
                            "7zip",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="uploadvideo",
            name="video",
            field=models.FileField(
                help_text="Formatos de video vÃ¡lidos: mp4, mkv, wmv, 3gp, f4v, avi, mp3",
                upload_to="course_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "mkv", "wmv", "3gp", "f4v", "avi", "mp3"]
                    )
                ],
            ),
        ),
    ]
