# Generated by Django 4.0.8 on 2025-11-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_create_default_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='schedule_by_day',
            field=models.JSONField(blank=True, default=list, help_text="Horarios por d?a, ej: [{'day': 'Lunes', 'start': '08:00', 'end': '10:00'}]."),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text="Lista de d?as de cursada (ej: ['Lunes','Mi?rcoles'])."),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
