# Generated by Django 5.1.2 on 2025-11-19 13:36

from django.db import migrations, models


def assign_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    roles = dict(
        ADMIN="ADMIN",
        STUDENT="STUDENT",
        TEACHER="TEACHER",
        COORDINATOR="COORDINATOR",
        BEDEL="BEDEL",
        MANAGEMENT="MANAGEMENT",
        PARENT="PARENT",
    )

    for user in User.objects.all():
        if user.is_superuser:
            user.role = roles["ADMIN"]
        elif user.is_student:
            user.role = roles["STUDENT"]
        elif user.is_lecturer:
            user.role = roles["TEACHER"]
        elif user.is_dep_head:
            user.role = roles["COORDINATOR"]
        elif user.is_parent:
            user.role = roles["PARENT"]
        else:
            user.role = roles["MANAGEMENT"]

        if user.role in {
            roles["BEDEL"],
            roles["MANAGEMENT"],
            roles["TEACHER"],
            roles["STUDENT"],
        }:
            user.is_role_active = user.is_active
        else:
            user.is_role_active = True

        user.save(update_fields=["role", "is_role_active"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dni",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_role_active",
            field=models.BooleanField(
                default=True,
                help_text="Activa o desactiva la participación según el rol (Bedel, Docente, etc.).",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("COORDINATOR", "Coordinador"),
                    ("BEDEL", "Bedel"),
                    ("MANAGEMENT", "Gestión"),
                    ("TEACHER", "Docente"),
                    ("STUDENT", "Alumno"),
                    ("PARENT", "Familiar"),
                ],
                default="MANAGEMENT",
                help_text="Define el tipo de usuario dentro del sistema.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="relation_ship",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Padre", "Padre"),
                    ("Madre", "Madre"),
                    ("Hermano", "Hermano"),
                    ("Hermana", "Hermana"),
                    ("Abuela", "Abuela"),
                    ("Abuelo", "Abuelo"),
                    ("Otro", "Otro"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("Tecnicatura", "Título de Tecnicatura"),
                    ("Licenciatura", "Título de Licenciatura"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.RunPython(assign_roles, migrations.RunPython.noop),
    ]
