# Generated by Django 5.1.2 on 2025-11-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_user_dni_user_emergency_contact_user_is_role_active_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_parent",
        ),
        migrations.DeleteModel(
            name="Parent",
        ),
    ]
