# Generated by Django 4.0.8 on 2025-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_turn_courseallocation_program_coursesection'),
        ('accounts', '0004_remove_user_is_parent_delete_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='programs_as_coordinator',
            field=models.ManyToManyField(blank=True, help_text='Carreras donde actúa como coordinador.', related_name='coordinators', to='course.program'),
        ),
        migrations.AddField(
            model_name='user',
            name='programs_as_teacher',
            field=models.ManyToManyField(blank=True, help_text='Carreras donde dicta clases.', related_name='teachers', to='course.program'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINATOR', 'Coordinador'), ('BEDEL', 'Bedel'), ('MANAGEMENT', 'Gestión'), ('TEACHER', 'Docente'), ('STUDENT', 'Alumno')], default='MANAGEMENT', help_text='Define el tipo de usuario dentro del sistema.', max_length=32),
        ),
    ]
