# Generated by Django 4.0.8 on 2025-11-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_programs_as_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachelor', 'Tecnicatura'), ('Master', 'Licenciatura')], max_length=25, null=True),
        ),
    ]
