# Generated by Django 4.0.8 on 2025-11-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='programs_as_coordinator',
        ),
    ]
