# Generated by Django 5.1.2 on 2025-11-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_student_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Debe cambiar la contraseña en el próximo inicio de sesión.",
            ),
        ),
    ]
