# Generated by Django 4.0.8 on 2025-11-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='legajo',
            field=models.CharField(blank=True, help_text='Número de legajo del estudiante (opcional).', max_length=50, null=True, verbose_name='Legajo'),
        ),
    ]
