from django.urls import path

from .views import (
    attendance_dashboard,
    dashboard_view,
    delete_post,
    edit_post,
    event_invitation_response,
    floor_create_view,
    floor_delete_view,
    floor_list_view,
    floor_update_view,
    home_view,
    post_add,
    room_create_view,
    room_delete_view,
    room_list_view,
    room_update_view,
    semester_add_view,
    semester_delete_view,
    semester_list_view,
    semester_update_view,
    session_add_view,
    session_delete_view,
    session_list_view,
    session_update_view,
)


urlpatterns = [
    # Accounts url
    path("", home_view, name="home"),
    path("add_item/", post_add, name="add_item"),
    path("item/<int:pk>/edit/", edit_post, name="edit_post"),
    path("item/<int:pk>/delete/", delete_post, name="delete_post"),
    path("item/<int:pk>/respond/", event_invitation_response, name="event_invitation_response"),
    path("attendance/dashboard/", attendance_dashboard, name="attendance_dashboard"),
    path("session/", session_list_view, name="session_list"),
    path("session/add/", session_add_view, name="add_session"),
    path("session/<int:pk>/edit/", session_update_view, name="edit_session"),
    path("session/<int:pk>/delete/", session_delete_view, name="delete_session"),
    path("semester/", semester_list_view, name="semester_list"),
    path("semester/add/", semester_add_view, name="add_semester"),
    path("semester/<int:pk>/edit/", semester_update_view, name="edit_semester"),
    path("semester/<int:pk>/delete/", semester_delete_view, name="delete_semester"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("infrastructure/floors/", floor_list_view, name="floor_list"),
    path("infrastructure/floors/add/", floor_create_view, name="floor_add"),
    path("infrastructure/floors/<int:pk>/edit/", floor_update_view, name="floor_edit"),
    path("infrastructure/floors/<int:pk>/delete/", floor_delete_view, name="floor_delete"),
    path("infrastructure/rooms/", room_list_view, name="room_list"),
    path("infrastructure/rooms/add/", room_create_view, name="room_add"),
    path("infrastructure/rooms/<int:pk>/edit/", room_update_view, name="room_edit"),
    path("infrastructure/rooms/<int:pk>/delete/", room_delete_view, name="room_delete"),
]
